import './globals.css'
import Header from "@/app/Header/page"
import ToastContext from '@/context/ToastCont'
import SessionContext from "@/context/getSession"


// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >
        <SessionContext>
          <ToastContext/>
        <Header/>
        {children}
        </SessionContext>
        </body>
    </html>
  )
}
